mysql:
  user: dbuser
  db: scans
  passwd: password123
  host: 1.255.0.0
  port: 1234

tmp_dir: /tmp/zonefiles
zonefile_dir: /var/spool/netscan/zonefiles
data_dir: "{home}/Documents/osint"

force_download: False # skip local file size comparission to remote file size, if no local file it will always download
czdap:
  base_url: https://czdap.icann.org
  zone_file_uri: /en/download-zone-data
  token: djbzklbvzklbkdvbzkdbkvbzkfvbzkvbzkjbjksdvb

ftp:
  - server: rz.verisign-grs.com
    user: abcdef
    passwd: 123456
    regex: '^([a-zA-Z0-9-]+)\s+NS\s+([a-zA-Z0-9-\.]+).$'
    files:
      - md5checksum: com.zone.gz.md5
        file_path: com.zone.gz
        tld: com
  - server: rzname.verisign-grs.com
    user: abcdef
    passwd: 123456
    regex: '^([a-zA-Z0-9-]+)\s+NS\s+([a-zA-Z0-9-\.]+).$'
    files:
      - md5checksum: master.name.zone.gz.md5
        file_path: master.name.zone.gz
        tld: name

force_persist: False # skip cache check for records.stale_days value, if cache miss it will always persist
records:
  regex: '^([a-zA-Z0-9-]+)[.]{1}([a-zA-Z0-9-]+)[.]{1}\s+(\d+)\s+in\s+ns\s+([a-zA-Z0-9-\.]+).$'
  cache_path: /var/cache/netscan/scans.db
  stale_days: 28


shodan_api_key: abcdef123456fedcba654321

osint:
  base_dir: "{home}/Documents/osint"
  shodan_dir: "{domain}/shodan/"
  whois_dir: "{domain}/whois/"
  dns_dir: "{domain}/dns/"
  https_dir: "{domain}/https/"
  spider_dir: "{domain}/spider/"